ALTER TABLE "NightCheck" DROP COLUMN IF EXISTS "temperatureMinC";
ALTER TABLE "NightCheck" DROP COLUMN IF EXISTS "temperatureMaxC";

ALTER TABLE "NightCheck" ADD COLUMN IF NOT EXISTS "windowsOpen" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "NightCheck" ADD COLUMN IF NOT EXISTS "fridgeTemp" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "NightCheck" ADD COLUMN IF NOT EXISTS "litterSampleTaken" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "NightCheck" ADD COLUMN IF NOT EXISTS "fireExtinguisher" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "NightCheck" ADD COLUMN IF NOT EXISTS "footDipChange" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "NightCheck" ADD COLUMN IF NOT EXISTS "dosatronCheck" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "NightCheck" ADD COLUMN IF NOT EXISTS "vitaminAdd" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "NightCheck" ADD COLUMN IF NOT EXISTS "vaccination" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "NightCheck" ADD COLUMN IF NOT EXISTS "medication" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "NightCheck" ADD COLUMN IF NOT EXISTS "pestControlInspection" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "NightCheck" ADD COLUMN IF NOT EXISTS "waterSanitizer" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "NightCheck" ADD COLUMN IF NOT EXISTS "calibrationWaterMeter" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "NightCheck" ADD COLUMN IF NOT EXISTS "calibrationTempProbe" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "NightCheck" ADD COLUMN IF NOT EXISTS "calibrationHumidityProbe" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "NightCheck" ADD COLUMN IF NOT EXISTS "calibrationWeigher" BOOLEAN NOT NULL DEFAULT false;